#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Cada novo elemento em uma sequência de Fibonacci é o resultado da soma dos dois últimos elementos
Começando por 1 e 2, os primeiros 10 elementos serão
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Considerando os elementos da sequência de Fibonacci que não ultrapassem 4 milhões,
encontre a soma dos elementos de valor par
'''
