#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Cada novo elemento em uma sequência de Fibonacci é o resultado da soma dos dois últimos elementos
Começando por 1 e 2, os primeiros 10 elementos serão
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Considerando os elementos da sequência de Fibonacci que não ultrapassem 4 milhões,
encontre a soma dos elementos de valor par
'''

UNTIL = 4000000
is_even: bool = lambda x: True if x % 2 == 0 else False

def fib_until_value(max_value: int):
    number_one = 1
    number_two = 1
    
    while number_one <= max_value:
        yield number_one
        number_one, number_two = number_two, number_one+number_two

fib_list = fib_until_value(UNTIL)

even_list = list(filter(is_even, fib_list))

# result
print(sum(even_list))