#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

A sequência de números triangulares é gerada pela adição de números naturais
Então o 7° número triangular é 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. Os primeiros 10 termos são
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Vamos listar os fatores dos primeiros 7 números triangulares
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
Podemos ver que 28 é o primeiro número triangular com mais de 5 divisores.
Qual é primeiro número triangular a ter mais de 500 divisores?
"""
